import os
print("a-sincota")
os.system("python ex03-a-SinCota.py")
print("b-sincota")
os.system("python ex03-c-SinCota.py")
# os.system("python ex03-a.py")
# os.system("python ex03-b.py")
# os.system("python ex03-c.py")
# os.system("python ex03-d.py")
# os.system("python ex03-e.py")